// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tcpfnjafbugmgvasuvfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcGZuamFmYnVnbWd2YXN1dmZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzkwODcsImV4cCI6MjA3Mjc1NTA4N30.lx7BrDdzCtBk9jr_xMqEZ9kSGLW6zFMtWY01cZ9Rhwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});